version: "2.4"
services:
  db:
    image: mysql:5.7
    restart: always
    networks:
      - wpsite
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db_data:/var/lib/mysql
  adminer:
    image: adminer:latest
    restart: always
    depends_on:
      - db
    networks:
      - wpsite
    ports:
      - 8080:8080
  wordpress:
    image: wordpress:latest
    restart: always
    depends_on:
      - db
    networks:
      - wpsite
    ports:
      - 8000:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wp_data:/var/www/html
networks:  
  wpsite: {}
volumes:
  db_data: {}
  wp_data: {}
